export const root='C:/Users/HP/Documents/Codex/2026-08-16/i/work/slides-build';
export const project='C:/Users/HP/Documents/Codex/2026-08-16/i/outputs/globalcommerce-enterprise-platform';
export const finalPath=project+'/docs/GlobalCommerce-Presentation-Jawad-Ahmad.pptx';
export const fullTitle='Design and Implementation of an Enterprise Cross-Border Digital Commerce Platform for Marketplace Management, Intelligent Inventory Optimization, AI-Assisted Demand Forecasting, International Order Processing, Logistics Visibility, and Executive Commerce Analytics';
export const slides=[
 {source:1,title:'GlobalCommerce',role:'opening thesis',
  say:'Good morning. My name is Jawad Ahmad. Today I am presenting GlobalCommerce, my EduQual Level 6 project. The project connects marketplace records, warehouse inventory, international orders, shipment tracking, demand forecasting and operational monitoring. I will first explain the business problem, then the design, and finally demonstrate one international order. The current implementation is a locally deployed proof of concept. Payments, exchange rates, trade charges and sales histories use simulated data; I am not presenting it as a production trading service.',
  show:'Begin on the title slide. Introduce yourself, look at the panel, and explain the purpose before listing technologies.',
  ask:'What is the project in one sentence? A shared operating workspace that connects an international order with its stock, shipment, forecast and service-health information.',
  sources:['docs/project-report.md','Oral Presentation Exam Guide.pdf','Exam topic PDF']},
 {source:2,title:'The business problem',role:'problem and business value',bullets:[
  'Separate systems make international orders difficult to coordinate.',
  'Stock reservations and shipment updates must stay connected.',
  'Demand uncertainty creates stockout and overstock risk.',
  'One workspace gives operations teams a shared view of each order.'],
  say:'Consider a customer placing an international order. The merchant needs to know whether stock is really available, what the total cost is, and where the shipment is. If these activities are disconnected, staff must reconcile the information manually. GlobalCommerce brings these records together. Its intended benefit is better coordination and more informed replenishment decisions. This is a design objective, not a measured claim that the prototype has already reduced costs or stockouts.',
  show:'Use a simple example: a UK customer buys two units from the warehouse with sufficient available stock.',
  ask:'How would you prove business value? Measure baseline and post-pilot stockouts, fulfilment time, forecast error and manual reconciliation effort.',sources:['docs/project-report.md']},
 {source:2,title:'What the prototype covers',role:'scope and implementation boundary',bullets:[
  'Marketplace: merchant, customer and product records.',
  'Operations: warehouse stock, international orders and shipment events.',
  'Decision support: demand forecasts and replenishment recommendations.',
  'Visibility: commerce views, Prometheus metrics and Grafana dashboards.'],
  say:'The prototype has four connected responsibilities. First, it stores marketplace records. Second, it processes inventory reservations and international orders, with a shipment event history. Third, it forecasts demand and proposes replenishment quantities. Fourth, it presents business and technical information. The demonstration uses three warehouse locations and five supported currencies. It does not connect to live payment, carrier or customs services. The source and documentation remain local at present; GitHub submission is a separate step that I will complete after review.',
  show:'Point out that the full formal project title is recorded in the title-slide notes. Explain implemented scope versus real-world integrations.',
  ask:'Why a prototype? It permits an end-to-end demonstration and architectural evaluation within the student hardware and time constraints.',sources:['docker-compose.yml','backend/app/main.py','docs/project-report.md']},
 {source:3,title:'System architecture',role:'architecture diagram',diagram:'architecture',
  intro:'A modular application with shared data and separate monitoring services.',callout:'Simple to run locally.\nClear boundaries to evolve.',
  say:'The browser runs a React-based console. It sends authenticated requests to a FastAPI application. PostgreSQL stores the business records, while Redis supports rate limiting. Forecasting runs in the application process. Prometheus collects service metrics, and Grafana visualizes those measurements. Docker Compose runs the six services. The design is a modular monolith at the application layer, not a microservice per business feature. This keeps deployment manageable on a 16 GB laptop. A future version could move heavy forecasting jobs to a separate worker and scale the API independently.',
  show:'Trace browser to API to database. Then trace API metrics to Prometheus to Grafana. Explain Redis separately from the database.',
  ask:'Why PostgreSQL? Orders, stock, payments and shipment records have relationships, and order creation needs transactional consistency. Why not microservices now? They add distributed failure and deployment complexity.',sources:['docker-compose.yml','backend/app/main.py','docs/architecture.md']},
 {source:3,title:'Inventory you can explain',role:'stock relationship diagram',diagram:'inventory',
  intro:'Available stock excludes units already promised to existing orders.',callout:'Reserve at order time.\nDeduct at delivery.',
  say:'On-hand stock means the physical quantity recorded in the warehouse. Reserved stock is committed to orders but has not yet been deducted on delivery. Available stock equals on hand minus reserved. In the illustrative example, 120 minus 3 gives 117 units available. The application locks the selected stock row and reserves stock within the order transaction. This is intended to protect against competing orders, but true concurrency behavior must be tested on PostgreSQL. The executive inventory card currently needs a calculation correction; the inventory table is the appropriate demonstration source.',
  show:'Use the equation, then point to the Inventory table in the live demo. These large example numbers are illustrative, not a screenshot measurement.',
  ask:'Why not deduct on hand immediately? Separating reservation from physical stock helps distinguish promised units from completed fulfilment. Cancellation and return rules need further work.',sources:['backend/app/services/order_service.py','backend/app/main.py']},
 {source:3,title:'One order, one workflow',role:'transaction sequence diagram',diagram:'order',
  intro:'Business records are created together; failures should not leave partial orders.',callout:'A repeat key returns\nthe existing order.',
  say:'The API validates the request and checks the idempotency key. A repeated key can return the existing order instead of intentionally creating another one. The system selects a warehouse based on available quantity and locks the stock row. It reserves the required units, computes the simulated charges, and creates the order, simulated payment authorization and shipment records in a transaction. If an error occurs, the database transaction should roll back. The current strategy does not optimize distance or shipping cost. Concurrent duplicate requests and cross-user key reuse require stronger validation.',
  show:'Follow the numbered sequence. During the demo, record the order ID and show the corresponding inventory reservation.',
  ask:'What does idempotency mean? Retrying the same logical request should not produce a second business operation. Explain why a client retry can happen after a network timeout.',sources:['backend/app/services/order_service.py','backend/tests/test_workflow.py']},
 {source:2,title:'International order costing',role:'cross border pricing rules',bullets:[
  'Supported currencies: USD, GBP, AED, PKR and EUR.',
  'Order total combines goods, shipping, duty and tax.',
  'Exchange rates, payment authorization and trade charges are simulated.',
  'Real launch requires current rates, legal rules and provider integrations.'],
  say:'International processing needs more than changing a currency symbol. This prototype stores an order currency and calculates goods, shipping, duty and tax. Its shipping rule is twelve dollars plus three point two dollars per kilogram. Duty is five percent of goods value; tax is eight percent of goods value plus duty. These are demonstration formulas, not real customs advice or country-specific tax rules. Payment authorization and capture are simulated. Production would require jurisdiction-specific rules, payment-provider integration, rounding policies and reliable exchange-rate history.',
  show:'Open a demo order and identify its currency and separate charge fields. Never call the mixed-currency dashboard total audited revenue.',
  ask:'Why retain currency per order? A numeric amount is ambiguous without currency, conversion basis and rounding rules.',sources:['backend/app/services/order_service.py']},
 {source:2,title:'Logistics visibility',role:'shipment traceability',bullets:[
  'Each order links to a shipment and tracking reference.',
  'Events record status, location, timestamp and a note.',
  'The UI progresses from creation through transit to delivery.',
  'Carrier integration and strict server-side transitions remain future work.'],
  say:'The logistics module makes shipment progress visible through an event history. Each event records the status, location, time and note. The intended path moves from created to picked, in transit, customs clearance, out for delivery and delivered. In the current demo, these events are entered manually. They do not come from a real carrier. The interface guides normal progression, but the backend still needs strict transition validation and duplicate-delivery protection. This is an important distinction between a visible workflow and a robust production state machine.',
  show:'Select the newly created shipment and advance it once. Show the added event. Do not repeat delivery calls during the demonstration.',
  ask:'What if the carrier sends the same event twice? Production needs a unique event ID, idempotent processing and allowed-transition rules.',sources:['backend/app/main.py','backend/app/services/order_service.py']},
 {source:3,title:'Demand forecasting',role:'forecast pipeline diagram',diagram:'forecast',
  intro:'Past sales become features, predictions and a replenishment signal.',callout:'Evaluate on later dates.\nDo not shuffle time.',
  say:'The model uses 120 days of synthetic sales history for each product and warehouse. Features include one-day, seven-day and fourteen-day lags, a shifted seven-day rolling average, weekday and trend. A Random Forest is trained using the earlier eighty percent of observations and evaluated on the later twenty percent. MAE measures the average absolute error in units; RMSE penalizes large errors more strongly. Multi-day predictions are generated recursively. The current one-step holdout evaluation is not a full backtest of the recursive seven-day workflow. The results show prototype behavior on synthetic data, not proven real-world forecast accuracy.',
  show:'Trace the stages, then show the actual MAE and RMSE produced by a run. Do not invent a percentage accuracy.',
  ask:'Why Random Forest? It handles nonlinear tabular patterns and runs on CPU. It still needs comparison with simple seasonal-naive and moving-average baselines.',sources:['backend/app/services/forecast_service.py','docs/model-evaluation.md']},
 {source:3,title:'From forecast to stock',role:'replenishment relationship diagram',diagram:'replenish',
  intro:'Suggested replenishment covers predicted demand plus a safety buffer.',callout:'Decision support.\nNo automatic purchase.',
  say:'The replenishment recommendation is the maximum of zero and forecast demand plus safety stock minus available stock. Suppose the seven-day demand prediction is sixty units, safety stock is fifteen, and available stock is fifty. The recommendation is twenty-five units. These numbers are illustrative. In the implementation, safety stock is derived from residual variation and the forecast horizon. This is a heuristic, not a calibrated service-level guarantee. The system proposes quantities; it does not place purchase orders. A formal approval workflow, supplier lead times, minimum order quantities and purchasing integration are future extensions.',
  show:'Explain each term before reading the result. During the demo, compare a forecast recommendation with the relevant warehouse balance.',
  ask:'Can the model be wrong? Yes. New promotions, changing demand and poor data can invalidate the pattern. A person should review recommendations; formal approval is not implemented.',sources:['backend/app/services/forecast_service.py']},
 {source:3,title:'Monitoring has three roles',role:'monitoring dataflow diagram',diagram:'monitoring',
  intro:'The console summarizes operations; monitoring explains service behavior.',callout:'One front door.\nDifferent responsibilities.',
  say:'The three views have different purposes. The commerce console is for business operations, such as orders, inventory and forecasts. Prometheus collects time-series measurements, such as request counts and durations. Grafana queries those measurements and makes them easier to investigate in charts. The custom Monitoring workspace brings selected technical signals into the same console. This combines access, not the responsibilities of the tools. A green card is not proof of historical uptime. The current hard-coded API-health label and shipment-status on-time proxy need replacement with measured definitions.',
  show:'Open Monitoring, explain requests per second, error rate and p95 latency, then follow the Grafana link. Explain that a quiet system can have little recent data.',
  ask:'What is p95 latency? Approximately ninety-five percent of observed requests fall at or below that duration in the selected measurement window.',sources:['backend/app/main.py','infrastructure/prometheus/prometheus.yml','infrastructure/grafana/dashboards']},
 {source:4,title:'The local operating workspace',role:'genuine application screenshot',
  say:'This is a genuine screenshot of the local Inventory page, captured during slide preparation. The navigation connects marketplace, inventory, orders, forecasting, analytics and monitoring. The table separates physical stock from reservations and available units. The Dubai control-hub row shows 180 on hand, 3 reserved and 177 available at the time of capture. The purpose of the screen is operational clarity, not decorative dashboard numbers. A screenshot is a backup illustration; the assessed demonstration should show an actual request and the corresponding persistent record change.',
  show:'Point out the selected Inventory page and the three quantity columns. Explain that live values may differ from the screenshot after new orders.',
  ask:'Why the bento-style interface? It organizes related information into scannable regions. Visual polish does not replace data correctness or usability testing.',sources:['frontend/app/page.tsx','Local UI screenshot captured 28 August 2026']},
 {source:2,title:'Security and accountability',role:'implemented security controls and boundaries',bullets:[
  'JWT authentication and Argon2 password hashing.',
  'Selected role checks, input validation and audit records.',
  'Redis-backed rate limiting and security response headers.',
  'Remaining: tenant isolation, production secrets and stronger authorization.'],
  say:'The project includes token-based authentication and password hashing. Some operations use role checks, input validation and audit records, and Redis supports request rate limiting. Authentication answers who the user is; authorization decides what they may do. A user having a token is not enough for safe access to every merchant record. Tenant ownership enforcement is incomplete. Before production, the project needs consistent object-level authorization, secure secrets, HTTPS, restricted network exposure, backup recovery tests and a formal security review. These controls do not mean the prototype is certified to an international standard.',
  show:'Explain one protected endpoint and an audit record. Do not display passwords, bearer tokens or local secret values in slides or screen sharing.',
  ask:'What is your biggest security gap? Consistent tenant and object ownership enforcement, alongside replacing demonstration credentials and exposed development settings.',sources:['backend/app/main.py','docs/security-and-standards.md','backend/tests/test_security.py']},
 {source:2,title:'Evidence before confidence',role:'test evidence and evaluation limits',bullets:[
  'Tests cover the normal order journey, repeated keys and forecast output.',
  'Security checks cover missing tokens, wrong passwords and headers.',
  'Demonstrate a stored change, not just a success message.',
  'Add concurrency, failure, authorization and multi-day forecast tests.'],
  say:'There are four automated test functions in the current suite. They cover a normal order journey, a repeated order key, forecast output and basic security behavior. A passing happy-path test does not prove correctness under concurrency or failure. The test suite uses SQLite, so it does not validate PostgreSQL row-lock behavior. I would add tests for simultaneous stock reservations, invalid shipment transitions, repeated delivery, unauthorized object access and failures during transaction creation. Forecast evaluation needs rolling, multi-day backtesting against baselines. No production load benchmark or real-business impact result is claimed.',
  show:'Before the exam, rerun the suite and keep the dated result. This slide describes test scope, not a claim of a fresh passing run.',
  ask:'What evidence is missing? PostgreSQL concurrency tests, stronger negative tests, load measurements, real-data model evaluation and a full live-demo rehearsal.',sources:['backend/tests/test_workflow.py','backend/tests/test_security.py','docs/testing.md']},
 {source:2,title:'Live demonstration',role:'end to end demonstration sequence',bullets:[
  '1. Show services, sign in, and inspect a warehouse stock balance.',
  '2. Create a two-unit GBP order; confirm the reservation and charges.',
  '3. Advance its shipment; show the persisted event history.',
  '4. Run a seven-day forecast; inspect Monitoring and Grafana.'],
  say:'I will now demonstrate one order from beginning to end. First I will show that the services are running and open the inventory balance. I will create a two-unit order for a UK destination in GBP and show the order ID, simulated charges and reserved units. Next I will advance the shipment and inspect its event history. Finally I will run a seven-day forecast and open the monitoring views. This connects the business workflow to its stored records and technical visibility. The current quantities may differ because this is a running demonstration system.',
  show:'Allow about five minutes if the exam timing permits. Open http://localhost:3000, http://localhost:8000/docs, http://localhost:3001 and http://localhost:9090 in advance. Verify every step before exam day. Do not run reset-demo during the assessment or erase existing records without reviewing the impact. Return to slide 16 afterward.',
  ask:'If the UI fails, use the documented API only if rehearsed. If using screenshots or a recording, identify them clearly as recorded evidence, not live execution.',sources:['docs/demo-script.md','docs/api-guide.md']},
 {source:2,title:'From prototype to production',role:'critical evaluation and prioritized improvements',bullets:[
  'Correct currency normalization, available-stock and on-time KPI definitions.',
  'Enforce tenant ownership, valid transitions and duplicate-delivery protection.',
  'Validate forecasts on real data; add baselines and multi-day backtests.',
  'Integrate providers, background jobs, backups and load-tested deployment.'],
  say:'The prototype connects the main workflow, but several issues must be addressed before production. First, the executive metrics require corrected definitions: mixed currencies must be normalized, available inventory must exclude reservations, and on-time delivery must use promised and actual dates. Second, the backend needs stronger tenant ownership and shipment transition rules, including duplicate-delivery protection. Third, forecasting needs real data and realistic multi-day evaluation. Finally, production needs live providers, asynchronous jobs, backups and load testing. These are prioritized engineering tasks, not features I am claiming are already finished.',
  show:'Lead with correctness, then security, then model quality and scale. Explain one specific fix if the panel asks for a redesign.',
  ask:'How would you scale? Separate forecast workers, make API replicas stateless, tune database queries and connection pools, introduce reliable integration events, then measure bottlenecks.',sources:['backend/app/main.py','backend/app/services/order_service.py','backend/app/services/forecast_service.py','docs/architecture.md']},
 {source:2,title:'Conclusion',role:'closing thesis and invitation',bullets:[
  'One connected journey: inventory, order, shipment and demand planning.',
  'A reproducible local stack with visible business and technical records.',
  'A clear distinction between working features and production readiness.',
  'Thank you. I welcome your questions and design challenges.'],
  say:'To conclude, GlobalCommerce demonstrates how an international order can connect to warehouse stock, shipment history, demand planning and operational monitoring. Its strongest contribution is the integrated workflow and the ability to explain how information moves through it. The present version is a local proof of concept using simulated external services and data. I have identified concrete correctness, security, evaluation and deployment improvements needed for production. Thank you for listening. I welcome your questions and I am ready to explain the implementation and discuss design changes.',
  show:'Stop here for the main presentation. Appendix slides 18 and 19 are for questions and preparation, not part of the main speech.',
  ask:'What did you learn? Answer personally and truthfully about the code paths you understand, decisions you reviewed and tests you can reproduce.',sources:['docs/project-report.md']},
 {source:2,title:'Appendix: design questions',role:'viva prompts and concise technical answers',bullets:[
  'Why not microservices? Local simplicity; split only when a real need appears.',
  'How to avoid overselling? Transactional reservations plus concurrency tests.',
  'Why not trust one accuracy score? Horizon, baseline and data quality matter.',
  'What happens on failure? Roll back, return a clear error, then retry safely.'],
  say:'Use this slide only if the viva turns to design tradeoffs. For each answer, use three parts: the decision, the reason, and the limitation. For overselling, explain the row lock and transaction, then acknowledge that SQLite tests cannot prove PostgreSQL concurrency. For forecasting, describe the chronological split and then the gap between one-step evaluation and recursive prediction. For failure handling, explain transactional rollback and idempotency, while identifying missing event retry and duplicate-delivery protection. If uncertain, say what you would inspect or test rather than inventing a guarantee.',
  show:'Practice these questions without reading the slide. Be ready to locate the corresponding source function and explain it line by line.',
  ask:'Unexpected redesign: if supplier lead time becomes twenty-one days, adapt the forecast horizon and inventory policy, then validate on matching multi-day holdouts.',sources:['backend/app/services/order_service.py','backend/app/services/forecast_service.py','docs/viva-preparation.md']},
 {source:2,title:'Appendix: evidence and tools',role:'evidence provenance and transparent assistance',bullets:[
  'Assessment sources: supplied exam guide, assigned topic and sample deck.',
  'Implementation evidence: source code, Compose configuration and test suite.',
  'AI tools assisted code, documentation and presentation preparation.',
  'The viva must demonstrate the student’s own understanding and verification.'],
  say:'The assessment guide allows AI assistance but requires the student to understand, justify and verify the work. AI tools assisted the preparation of code, documentation and these presentation materials. That assistance is not a substitute for my own understanding. Before presenting, I need to personally review the code, run the system, reproduce the tests and be able to explain the design and limitations. I should describe only the checks I actually completed. The slides contain source references in their notes, and the screenshot is from the local application rather than a mock-up.',
  show:'Preparation checklist: rehearse opening and closing; verify demo data; rerun tests; review the critical code; prepare a clearly labelled backup recording; review submission rules; upload to your own GitHub repository only when satisfied. Replace any personal speaking claims with wording that is true for you.',
  ask:'How were tools used? Explain exactly which work was assisted, what you changed or reviewed, and what evidence you independently checked. Do not claim unaided authorship.',sources:['Oral Presentation Exam Guide.pdf','Sample Presentation EduQual Diplomas (1).pptx','docs/project-report.md']}
];
