import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {applyPresentationChartFont,finalizePresentation} from 'file:///C:/Users/HP/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations/container_tools/artifact_tool_utils.mjs';
const workspace='C:/Users/HP/Documents/Codex/2026-08-16/i';
const project=workspace+'/outputs/globalcommerce-enterprise-platform';
const build=workspace+'/work/slides-build/exam-v2';
const output=workspace+'/test presentation';
const skill='C:/Users/HP/.codex/plugins/cache/openai-primary-runtime/presentations/26.905.11957/skills/presentations';
await fs.mkdir(build,{recursive:true});
const evidence=JSON.parse(await fs.readFile(project+'/reports/verification/forecast-evaluation.json','utf8'));
const series=evidence.series[0];
const p=Presentation.create({slideSize:{width:1280,height:720}});
const ink='#112633', muted='#52616A', accent='#C8452D', pale='#F2F5F6';
const all=[];
function text(s,t,x,y,w,h,size=28,color=ink,bold=false){
 const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});
 q.text=t;q.text.style={typeface:'Arial',fontSize:size,color,bold,autoFit:'none',wrap:'square',insets:{left:0,right:0,top:0,bottom:0},verticalAlignment:'middle'};return q;
}
function slide(title){const s=p.slides.add();s.background.fill='#FFFFFF';text(s,title,64,43,1110,90,44,ink,true);text(s,String(p.slides.items.length).padStart(2,'0'),1165,657,50,26,18,muted);return s;}
function sub(s,t){text(s,t,64,143,1120,64,26,muted);}
function rows(s,items){items.forEach((a,i)=>{let y=230+i*87;text(s,a[0],64,y,340,62,27,ink,true);text(s,a[1],435,y,752,70,26);});}
function foot(s,t){text(s,t,64,615,1080,43,19,muted);}
function box(s,t,x,y,w,h){const q=s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill:pale,line:{fill:'#A9B6BB',width:1.3}});text(s,t,x+14,y+8,w-28,h-16,25,ink,true);return q;}
function arrow(s,x,y,w,h,down=false){s.shapes.add({geometry:down?'downArrow':'rightArrow',position:{left:x,top:y,width:w,height:h},fill:accent,line:{fill:'none',width:0}});}
function table(s,values,widths,y=235,h=320){const t=s.tables.add({rows:values.length,columns:values[0].length,left:64,top:y,width:1120,height:h,columnWidths:widths,values});t.borders.assign({fill:'#D4DEE2',width:1,style:'solid'});for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){const cell=t.getCell(r,c);cell.fill=r===0?ink:r%2===1?pale:'#FFFFFF';cell.text.style={typeface:'Arial',fontSize:25,bold:r===0,color:r===0?'#FFFFFF':ink,verticalAlignment:'middle',insets:{left:14,right:14,top:9,bottom:9}};}return t;}
function notes(s,title,time,say,show,question,refs=[]){const n=`${title}\nSuggested time: ${time}\n\nSAY IN YOUR OWN WORDS\n${say}\n\nSHOW / TRANSITION\n${show}\n\nIF ASKED\n${question}\n\nSOURCES\n${refs.map(r=>r.startsWith('http')?r:project+'/'+r).join('\n')}\n`;s.speakerNotes.textFrame.setText(n);all.push(n);}
let s=slide('GlobalCommerce');
text(s,'Enterprise cross-border\ndigital commerce platform',64,235,1080,150,57,ink,true);
text(s,'Jawad Ahmad\nEduQual Level 6 Diploma in Artificial Intelligence Operations',64,453,1110,95,28);
foot(s,'Local working prototype with simulated external commerce services');
notes(s,'1. Introduction','40 seconds','Assalamualaikum. My name is Jawad Ahmad. This project connects marketplace management, inventory, international orders, logistics visibility, demand forecasting and executive analytics. I will explain the business problem, trace an order through the architecture, and demonstrate the working local system. Payments and carrier services use simulations in this prototype.','Introduce the topic without reading the full assigned title.','Formal assigned title: Design and Implementation of an Enterprise Cross-Border Digital Commerce Platform for Marketplace Management, Intelligent Inventory Optimization, AI-Assisted Demand Forecasting, International Order Processing, Logistics Visibility, and Executive Commerce Analytics.',['docs/requirements-traceability.md']);
s=slide('Business problem');sub(s,'Separate records make international commerce harder to control.');rows(s,[['Stock uncertainty','Businesses can accept orders for units already promised.'],['Cross-border complexity','Currencies and landed costs complicate checkout.'],['Limited delivery visibility','Teams struggle to explain where an order stands.'],['Uncertain demand','Excess stock ties up money. Shortages lose sales.']]);
notes(s,'2. Business problem','65 seconds','Imagine a seller serving customers in different countries while storing products in several warehouses. Separate stock sheets and order records can disagree. Staff may promise the same stock twice or struggle to explain a delayed delivery. Demand uncertainty creates both excess stock and shortages. My prototype addresses these problems through linked records, controlled workflows and forecast evidence. I have not measured a commercial cost saving, so I will not claim one.','Connect each problem to a function you will demonstrate later.','Who benefits? Operations staff need reliable stock and delivery records. Managers need clearly defined reports. Customers need orders the business can fulfil.',['docs/project-report.md']);
s=slide('Project scope and presentation roadmap');sub(s,'Five business modules share one local application and database.');table(s,[['Module','Evidence in this presentation'],['Marketplace management','Seller verification and customer access'],['Inventory management','Warehouse balances and stock movements'],['International orders and logistics','Reservation, charges, delivery and cancellation'],['AI-assisted demand forecasting','History, baseline, error and replenishment'],['Executive analytics','Financial definitions and operational exports']],[440,680],222,345);foot(s,'Roadmap: business problem, architecture, evidence, limitations, live demonstration');
notes(s,'3. Scope','45 seconds','The five modules correspond to the assigned project. They work together through shared records rather than separate disconnected dashboards. I will explain the data flow first, then the order and stock rules, forecasting and verification. Technical monitoring supports these business modules. It is not a substitute for business analytics.','Point to each module once. Keep the roadmap brief.','The local proof of concept supports the assessed workflows. Real payment and carrier integrations, split shipments, returns and production capacity require further work.',['docs/requirements-traceability.md']);
s=slide('System architecture');sub(s,'A modular backend handles business rules and forecasting.');
box(s,'React\nUser interface',64,244,280,100);arrow(s,354,280,52,24);box(s,'FastAPI\nBusiness logic + AI',416,244,322,100);arrow(s,748,280,52,24);box(s,'PostgreSQL\nBusiness records',810,244,330,100);
arrow(s,475,349,24,58,true);box(s,'Redis\nRequest limiting',416,415,240,92);arrow(s,680,349,24,58,true);box(s,'Prometheus\nAPI measurements',684,415,256,92);arrow(s,950,448,40,24);box(s,'Grafana\nGraphs',1000,415,190,92);foot(s,'Docker Compose runs six local services. Responses return to the interface.');
notes(s,'4. System architecture','85 seconds','React is the website the user interacts with. It sends requests to FastAPI, which checks identity, applies business rules and uses PostgreSQL to store records. Forecasting runs inside the backend. Redis supports request limiting. Prometheus collects API measurements and Grafana displays them. The database and API exchange data in both directions even though this overview emphasises request flow. Docker Compose runs six local services. A modular backend keeps this laptop demonstration easier to run. The trade-off is that forecasting shares resources with business requests.','Trace one request across the top row, then explain the monitoring branch.','Why not microservices? Independent scaling can help a larger deployment, but it adds network, deployment and consistency complexity. I would separate a forecasting worker when measured workload justifies it.',['docker-compose.yml','backend/app/main.py','backend/app/services/forecasting.py']);
s=slide('Marketplace and access control');sub(s,'The server checks the user’s role and ownership of records.');table(s,[['Actor','Example responsibility or boundary'],['Administrator','Verify sellers and manage accounts and catalogue'],['Merchant','Manage owned products and view own sales report'],['Customer','Create orders and access own order records'],['Warehouse and logistics staff','Perform permitted stock and shipment operations']],[380,740]);foot(s,'A verified seller can supply active products. A hidden button alone is not security.');
notes(s,'5. Marketplace and access','60 seconds','The Marketplace page identifies registered sellers and customers. Administration provides account and catalogue controls. Authentication identifies the user. Authorization determines what that user may do and which records they may access. The API enforces these rules, not only the interface. Customers should see their own order records. Merchants have ownership restrictions on products and reports. Staff receive operational permissions according to role.','If asked, show Marketplace and Administration. Do not spend demo time creating multiple accounts.','A modified browser request must still pass backend role and ownership checks. Staff access remains broad in parts of this prototype and should become more narrowly scoped for production.',['backend/app/access.py','backend/app/administration.py','backend/tests/test_completion.py']);
s=slide('Inventory rules');sub(s,'Available stock = on hand − reserved');table(s,[['Illustrative stage','On hand','Reserved','Available'],['Before order','100','0','100'],['After reserving 2 units','100','2','98'],['After delivering those units','98','0','98']],[550,190,190,190],245,280);foot(s,'Illustrative figures. This prototype deducts on-hand stock at delivery.');
notes(s,'6. Inventory rules','75 seconds','On hand is the recorded physical-stock balance. Reserved units are promised to existing orders. Available equals on hand minus reserved. Here, ordering two units changes reserved from zero to two and available from one hundred to ninety-eight. Delivery decreases both on hand and reserved by two. Available stays ninety-eight because the order already reserved those units. Cancellation before dispatch releases reserved units. A stock receipt increases on hand. These example numbers are not the live database totals.','During the demo record the actual starting balance for the allocated product and warehouse.','Why deduct on hand at delivery? It simplifies this assessment workflow. A production design would distinguish warehouse stock from stock in transit.',['backend/app/services/orders.py','docs/user-guide.md']);
s=slide('Order transaction and safe retries');sub(s,'The backend commits the order and reservation together.');
box(s,'1  Validate user\nand request key',64,240,334,106);arrow(s,408,280,42,23);box(s,'2  Lock stock\nand choose warehouse',460,240,334,106);arrow(s,804,280,42,23);box(s,'3  Reserve units\nand calculate charges',856,240,334,106);
text(s,'Commit',64,411,270,55,32,accent,true);text(s,'Order, payment simulation, shipment and audit record',365,405,800,78,28);text(s,'Failure / retry',64,511,270,55,32,accent,true);text(s,'Roll back an error. Return the same order for a matching retry.',365,500,800,89,28);foot(s,'One warehouse must supply the whole order. Allocation favours available quantity.');
notes(s,'7. Order transaction','80 seconds','The API validates the customer and request. It locks the customer before checking the repeat key, then locks candidate stock rows in a consistent order. It chooses one warehouse that can supply all items. Reservation, costs, order, simulated payment, shipment and audit data belong to one transaction. An error rolls back uncommitted changes. If the browser retries a request with the same key and matching details, the API returns the existing order. If the details differ, it rejects the conflict.','Explain idempotency using a lost network response rather than unexplained jargon.','Two buyers requesting the last item must not both reserve it. Database locking and a check of available stock protect the transaction. PostgreSQL concurrency evidence covers tested duplicate and competing requests.',['backend/app/services/orders.py','reports/verification/postgres-concurrency.json']);
s=slide('International checkout');sub(s,'The order records its currency, exchange rate and charge components.');table(s,[['Component','Illustrative GBP amount'],['Goods','100.00'],['Shipping','12.00'],['Duty: 5% of goods','5.00'],['Tax: 8% of goods plus duty','8.40'],['Total checkout value','125.40']],[800,320],222,346);foot(s,'Illustrative component arithmetic. Rates and charges are simulated, not live trade rules.');
notes(s,'8. Cross-border checkout','55 seconds','International checkout needs a clear breakdown. This example shows goods of one hundred pounds, shipping of twelve, duty of five and tax of eight pounds forty, giving a total of one hundred twenty-five pounds forty. This is an illustrative charge breakdown, not a live quotation. The implementation uses fixed simulated exchange rates and charge rules and saves the rate used by each order. Reports convert amounts using that saved rate.','Show the actual order breakdown during the live demo. Explain merchandise value versus checkout value.','Shipping in the implementation depends on weight before currency conversion. Production needs authoritative provider rates and tax rules, as well as fixed-precision monetary database fields.',['backend/app/services/orders.py','backend/app/administration.py']);
s=slide('Logistics visibility');sub(s,'A tracking reference and event history connect each shipment to its order.');
table(s,[['Normal progression','What the operator can explain'],['Created, then picked','The warehouse prepares the order'],['In transit, then customs','The shipment progresses across borders'],['Out for delivery, then delivered','The final delivery completes the workflow'],['Delay and recovery','Valid transitions preserve the event history']],[575,545]);foot(s,'Carrier events and payment capture are simulated. The API rejects repeated delivery.');
notes(s,'9. Logistics','60 seconds','Each order links to a shipment and tracking reference. The normal progression is created, picked, in transit, customs clearance, out for delivery and delivered. Each event records its status, time, location and note. The backend validates transitions. In-transit stages can record delays and later recover. Delivery deducts stock and captures the simulated payment once. Dispatch prevents cancellation. There is no live carrier connection in this prototype.','Show event history, rather than only clicking through status buttons.','A real carrier integration needs authenticated callbacks, durable provider-event IDs, deduplication and handling for events that arrive out of order.',['backend/app/services/orders.py','docs/demo-script.md']);
s=slide('Demand forecasting method');sub(s,'Past sales inform a future estimate for each product and warehouse.');
box(s,'Daily sales history\nSeeded or imported CSV',64,237,325,110);arrow(s,399,280,40,23);box(s,'Past lags and\nrolling demand features',449,237,325,110);arrow(s,784,280,40,23);box(s,'Random Forest versus\nweekly baseline',834,237,356,110);
text(s,'Earlier 80% trains',64,402,490,54,34,ink,true);text(s,'Later 20% evaluates',654,402,520,54,34,ink,true);text(s,'The lower holdout MAE selects the forecast model.',64,483,1120,65,30,accent,true);foot(s,'Orders do not automatically update training history. The same holdout also selects the model.');
notes(s,'10. Forecast method','90 seconds','History comes from a separate seeded or imported daily-sales dataset. Eligible series require at least thirty-five observations and recent history. Features include demand one, seven and fourteen days ago, a shifted seven-day mean, weekday and trend. Earlier dates train the model and later dates form the holdout. Predictions proceed recursively without inserting future actual values. A weekly baseline repeats the last training week. The lower mean absolute error chooses the model, which then refits on available history and forecasts tomorrow onward.','Explain that a new operational order changes stock but does not automatically retrain the model.','The same holdout supports model selection, so it is not an independent final test. Real deployment requires representative data and rolling-origin evaluation. Random Forest is an algorithm. TensorFlow is a framework, not automatically a better model.',['backend/app/services/forecasting.py','docs/model-evaluation.md']);
s=slide('Recorded forecast evidence');sub(s,'NT-NOISE-01 / DXB-01: one product and warehouse in the synthetic test dataset');
const chart=s.charts.add('bar',{position:{left:64,top:240,width:670,height:338},categories:['Random Forest','Weekly baseline'],series:[{name:'MAE (units/day)',values:[series.mae,series.baseline_mae],fill:accent}],hasLegend:false,barOptions:{direction:'column',grouping:'clustered'},dataLabels:{showValue:true,position:'outEnd',textStyle:{typeface:'Arial',fontSize:24,bold:true}},xAxis:{textStyle:{typeface:'Arial',fontSize:23}},yAxis:{min:0,max:2,majorUnit:0.5,numberFormatCode:'0.0',textStyle:{typeface:'Arial',fontSize:21},title:{text:'MAE (units/day)',textStyle:{typeface:'Arial',fontSize:23}}},chartFill:'#FFFFFF',chartLine:{fill:'none',width:0}});applyPresentationChartFont(chart,{fontFamily:'Arial'});
text(s,'Lower error is better',780,249,420,47,29,ink,true);text(s,`96 training days\n24 holdout days\n\nForest RMSE: ${series.rmse.toFixed(3)}\nSelected: Random Forest`,780,319,420,214,27);foot(s,'Saved run: 6 September 2026. Synthetic data does not establish commercial accuracy.');
notes(s,'11. Forecast evidence','80 seconds',`This chart uses the saved test evidence, not invented accuracy. For ${series.series}, the Random Forest MAE is ${series.mae} units per day compared with ${series.baseline_mae} for the weekly baseline. Training covers ninety-six days and the holdout covers twenty-four days, from ${series.test_start} to ${series.test_end}. MAE means average absolute unit error. RMSE penalises larger errors. This run uses deterministic synthetic data. The current UI evaluation may differ because it has a different run date or dataset. The figures demonstrate evaluation, not proven real-business accuracy.`,'Point to the units and compare both bars. Do not describe MAE as a percentage accuracy.','A lower MAE is useful but insufficient alone. Check each series, seasonality, stockout effects and longer-horizon errors. Forecast ranges are illustrative rather than calibrated confidence intervals.',['reports/verification/forecast-evaluation.json','docs/model-evaluation.md']);
s=slide('Replenishment and management decisions');sub(s,'A person reviews each stock recommendation before acting.');
text(s,'60 + 15 − 50 = 25 units',64,238,1110,90,58,accent,true);text(s,'Forecast demand + safety stock − available stock',64,348,1110,62,32);text(s,'Illustrative recommendation: receive 25 additional units',64,449,1110,68,32,ink,true);foot(s,'Floor at zero. Stock at forecast time may differ from current stock.');
notes(s,'12. Replenishment','60 seconds','This example shows forecast demand of sixty units, safety stock of fifteen and available stock of fifty. The recommendation is twenty-five units. The actual formula floors the result at zero. Safety stock uses forecast error and horizon as a heuristic. The UI labels stock at run time separately from current available stock, because new orders may change inventory after a forecast. Recommendations do not automatically create purchase orders.','Identify one real recommendation during the demonstration and explain its rationale.','Supplier lead times, minimum purchase quantities, service-level calibration and procurement approval remain future improvements. Rerun forecasting after relevant stock or history changes.',['backend/app/services/forecasting.py','frontend/app/components/Insights.tsx']);
s=slide('Analytics and monitoring');sub(s,'Business reports and service measurements answer different questions.');table(s,[['Business analytics','Technical monitoring'],['Orders and units','API requests per second'],['Goods value versus checkout total','p95 response time'],['Available stock by warehouse','Response codes and server errors'],['Delivery completion and CSV exports','Prometheus measurements and Grafana graphs']],[560,560]);foot(s,'Delivery completion differs from on-time delivery. API requests differ from orders.');
notes(s,'13. Analytics and monitoring','60 seconds','Business analytics shows orders, stock, financial totals and delivery completion. Merchandise value counts goods. Checkout value includes shipping, duty and tax. Technical monitoring measures API traffic, latency and errors. One order can cause several API calls, so request counts cannot be called order counts. P95 is approximately the response duration within which ninety-five percent of measured requests finish. It is not an average. Sparse graphs just after startup may need time to collect measurements.','During the demo show one business figure and one technical graph.','If latency rises, first confirm the affected endpoints and time window, inspect errors and logs, then examine database work and resource pressure. A slow graph does not by itself identify the cause.',['backend/app/administration.py','frontend/app/components/Insights.tsx','docs/user-guide.md']);
s=slide('Security and failure handling');sub(s,'Controls protect the workflow, with explicit prototype limitations.');rows(s,[['Unauthorized access','JWT, password hashes and server-side ownership checks'],['Conflicting stock updates','Transactions, locks and validated lifecycle transitions'],['Interrupted requests','Stable retry keys and checks of persisted order state'],['Service or data failure','Health checks, logs, backups and a tested restore copy']]);foot(s,'Production still needs TLS, MFA and managed secrets. Redis failure permits requests.');
notes(s,'14. Security and recovery','85 seconds','Passwords use hashes and the API checks active users, roles and ownership. Transactions protect stock updates. Retry keys help when a response is lost. If the database is unavailable, the application cannot safely accept orders. I would check health and logs, restore service, inspect saved state and only then retry. Backup recovery has been tested into a separate database, preserving the live data. This local deployment uses HTTP, demo credentials and broad staff permissions in places. If Redis fails, the current rate limiter fails open. That preserves availability but temporarily weakens traffic protection.','Explain one failure scenario directly. Keep passwords, tokens and private data off shared source-code screens.','Production would need TLS, MFA, managed secrets, tighter staff scopes, rate-limit fallback policy, independent security review and tested recovery objectives. Do not claim certification.',['backend/app/main.py','backend/app/access.py','scripts/restore-backup-copy.ps1','docs/security-and-standards.md']);
s=slide('Verification evidence and boundaries');sub(s,'Recorded results support specific claims, rather than complete correctness.');table(s,[['Evidence','Result and scope'],['Backend regression','20 passed, 6 September 2026'],['Application line coverage','89.91%: 1,337 of 1,487 lines'],['PostgreSQL concurrency','Duplicate requests, competing stock and delivery'],['Forecast evaluation','9 synthetic series, dated model and baseline errors']],[460,660],226,300);foot(s,'No production load test. Full container OS scan and final live rebuild remain unverified.');
notes(s,'15. Verification','70 seconds','The saved backend suite passed twenty tests on six September. Coverage is eighty-nine point nine one percent of application lines, not a probability of correctness. Most functional tests use isolated SQLite databases. Separate PostgreSQL concurrency checks verify the tested repeat-request, overselling and delivery scenarios. Forecast evidence covers nine synthetic series. Dated package and source scans exist, but the full container OS scan timed out. On nineteen September source-contract and TypeScript checks passed, while the final production rebuild hit a permission error and Docker was unavailable. I must rerun and check the final local build before the exam.','If questioned, open reports/verification/README.md and its supporting files. Update verbal status only after reproducing a successful new check.','These checks do not prove five million transactions per day, complete browser coverage or real-data forecast accuracy. No production load or formal penetration test has established those claims.',['reports/verification/README.md','reports/verification/backend-tests.xml','reports/verification/coverage.xml','reports/verification/postgres-concurrency.json','docs/completion-checklist.md']);
s=slide('AI assistance and prototype limits');sub(s,'AI supports the work. The presenter must explain and defend every claim.');
text(s,'AI assistance',64,231,490,55,33,ink,true);text(s,'Code and configuration drafting\nDocumentation and slide preparation\nDebugging and test assistance',64,316,515,165,28);
text(s,'Current boundaries',665,231,515,55,33,ink,true);text(s,'Simulated payments and carrier events\nSynthetic or imported sales history\nLocal deployment with demo settings\nNo measured enterprise-scale capacity',665,308,525,220,28);foot(s,'Personal ownership means understanding decisions and reproducing the checks.');
notes(s,'16. Responsible AI and limits','60 seconds','I used AI assistance for coding, configuration, documentation, debugging and presentation preparation. I will describe exactly what I personally reviewed and tested, without claiming that every line or diagram was independently authored. My responsibility in this assessment is to understand the design, demonstrate its behaviour and defend its limits. External payment and carrier services use simulations. The forecasting evidence uses synthetic data. Production deployment requires stronger security, real integrations and measured capacity.','Before presenting, practise explaining every named component and reproduce the core demonstration yourself.','If asked what you changed personally, give a specific truthful example. If you do not know an answer, state what you know and explain how you would investigate.',['AI_USAGE.md','docs/completion-checklist.md']);
s=slide('Live demonstration');sub(s,'One customer orders two units. Every step has a visible result.');table(s,[['Time','Action','Visible evidence'],['0:00–0:40','Starting stock','On hand, reserved and available'],['0:40–2:40','Order and delivery','Order ID, charges, stock changes and history'],['2:40–3:30','Forecasting','Model error and stock recommendation'],['3:30–4:15','Pre-dispatch cancellation','A separate order releases reserved units'],['4:15–5:00','Analytics and monitoring','Business totals versus API measurements']],[185,390,545],218,350);foot(s,'Use the EXE launcher before the exam. Keep the slides and website open.');
notes(s,'17. Live demonstration','5 minutes, separate from the slide talk','Sir, I will now demonstrate one international order from creation to delivery. First I will record the product stock. I will create a two-unit order and show its order number, charges and allocated warehouse. Reserved stock should increase by two and available stock should decrease by two. At delivery, on hand and reserved should each fall by two. Then I will explain one forecast recommendation. A separate cancellation example will release a reservation. Finally I will distinguish business analytics from API monitoring.','Use Alt+Tab. Check the allocated warehouse rather than an unrelated balance. Rehearse the product and valid statuses. If forecasting is slow, identify and show a saved evaluation honestly. Refresh after a network error to inspect state before retrying. Never reset the database during the exam.','If time is shortened, prioritise order creation, stock proof and delivery. Keep a labelled backup recording or screenshots ready, without representing them as live.',['docs/demo-script.md','scripts/ExamLauncher.cs']);
s=slide('Conclusion');sub(s,'The prototype connects the core commerce workflow.');rows(s,[['Demonstrated value','Linked orders and inventory reduce conflicting records.'],['Decision support','Forecast comparisons inform replenishment decisions.'],['Operational evidence','History, reports and monitoring make behaviour inspectable.'],['Next stage','Real integrations, stronger security and measured scaling.']]);
notes(s,'18. Conclusion','35 seconds','GlobalCommerce brings the key business records and workflows into one local system. The demonstration links an order to its stock reservation, simulated charges, delivery history and inventory update. Forecast comparisons support planning and monitoring helps investigate technical problems. The next stage is real integrations, representative data, stronger security and measured scaling. Thank you. I welcome questions about the design, evidence and limitations.','Stop here for the main presentation. The remaining slides support questions.','Explain the business benefit without inventing percentages of savings, uptime or capacity.',['docs/project-report.md']);
s=slide('Appendix: architecture trade-offs');sub(s,'Decisions fit a local prototype. Production changes need evidence.');table(s,[['Decision today','Reason','Future extension'],['One modular API','Simple deployment and shared transactions','Forecast worker when load justifies it'],['One warehouse per order','Simpler allocation and shipment consistency','Split fulfilment and multi-shipment state'],['Deduct stock at delivery','Clear assessment lifecycle','Warehouse and in-transit stock ledgers'],['Human-reviewed forecasts','Avoid unchecked automated purchasing','Lead times, approval and calibrated policies']],[310,405,405],222,350);
notes(s,'19. Design defence','Q&A only','Answer with a decision, its reason, supporting evidence and its limitation. These choices simplify a laptop-based assessment. They do not establish that the same design is sufficient at enterprise scale. Any redesign should preserve stock consistency and make failure handling explicit.','Use this slide if the examiner asks why you chose the architecture or how it would evolve.','For a twenty-one-day supplier lead time, extend and evaluate the relevant forecast horizon and stock policy. For growth, measure bottlenecks before adding caches, workers or replicas.',['docs/architecture.md','docs/model-evaluation.md']);
s=slide('Appendix: evidence and assessment references');
text(s,'Project evidence',64,216,515,55,31,ink,true);text(s,'reports/verification/README.md\ndocs/model-evaluation.md\ndocs/requirements-traceability.md\ndiagrams/index.html\nAI_USAGE.md',64,292,550,238,25);
text(s,'Assessment references',665,216,525,55,31,ink,true);text(s,'Supplied oral presentation exam guide\nAssigned project topic document\nSample oral exam: Talha Nawaz\nYouTube: tMiNZTVoy5c',665,292,515,204,25);foot(s,'Presentation: 25 marks. Interview: 25 marks. Slides alone cannot guarantee a score.');
notes(s,'20. Sources and preparation','Q&A only','The supplied guide allocates equal presentation weight to content mastery, organisation, presentation skills, visuals and responsible AI use. The sample exam provides useful evidence about question style and demonstration pacing, but it is not a guarantee of identical questions or marks. The examiner expects independent reasoning and may ask for a redesign.','Before the exam: complete the local build, test the launcher, rehearse the full workflow, verify all linked files, and prepare your repository according to college requirements. Nothing has been uploaded automatically.','Sample exam observations use an auto-generated transcript and supplied screenshots. Transcript wording may contain errors. The result announcement is around 1:10:54.',['docs/requirements-traceability.md','reports/verification/README.md','https://www.youtube.com/watch?v=tMiNZTVoy5c&t=434s','https://www.youtube.com/watch?v=tMiNZTVoy5c&t=2436s','https://www.youtube.com/watch?v=tMiNZTVoy5c&t=4254s']);
await fs.writeFile(build+'/speaker-notes.txt',all.join('\n\n========================================\n\n'));
const candidate=build+'/candidate.pptx';await(await PresentationFile.exportPptx(p)).save(candidate);
for(let i=0;i<p.slides.items.length;i++){const s=p.slides.items[i];await fs.writeFile(build+`/slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await(await p.export({slide:s,format:'png',scale:1})).arrayBuffer()));console.log('Rendered',i+1);}
const finalPath=output+'/GlobalCommerce-Exam-Focused-Jawad-Ahmad.pptx';
await finalizePresentation({workspaceDir:workspace,candidatePath:candidate,finalPath,pythonExecutable:'C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[3,5,6,8,9,13,15,17,19].flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:20,requiredNativeTableOwnerSlides:[3,5,6,8,9,13,15,17,19],requiredNativeChartOwnerSlides:[11],fontPolicy:{basis:'design',families:['Arial']},materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:build+'/validation.json'});
await fs.copyFile(build+'/speaker-notes.txt',output+'/New-Slides-Speaker-Notes.txt');
console.log('FINAL',finalPath);
